export const translations = {
  en: {
    languageLabel: "Language / भाषा",
    studentLogin: "Student Login",
    welcome: "Welcome",
    subWelcome: "Online School Exam Management System",
    emailOrMobile: "Email or Mobile Number",
    placeholderEmailMobile: "Enter your email or mobile number",
    password: "Password",
    placeholderPassword: "Enter password",
    showPassword: "Show Password",
    signIn: "Sign In",
    authenticating: "Authenticating...",
    areYouStudent: "Are you a student?",
    registerHere: "Register here",
    studentRegistration: "Student Registration",
    subRegister: "Register to join the examinations",
    fullName: "Full Name",
    placeholderName: "Enter your name",
    firstName: "First Name",
    lastName: "Last Name",
    placeholderFirstName: "Enter first name",
    placeholderLastName: "Enter last name",
    errFirstNameInvalid: "First name must be between 1 and 25 characters and contain only letters and spaces",
    errLastNameInvalid: "Last name must be between 1 and 25 characters and contain only letters and spaces",
    schoolUdise: "School Name / UDISE No.",
    placeholderSearchSchool: "Type school name or UDISE to search...",
    classClassroom: "Class / Classroom",
    selectClass: "-- Select Class --",
    selectSchoolFirst: "Please select school first.",
    district: "District",
    tehsil: "Tehsil",
    mobileUnique: "Mobile Number (Unique Login ID)",
    placeholderMobile: "10-digit mobile number",
    choosePassword: "Choose password",
    registering: "Registering...",
    errNameInvalid: "Name must be between 2 and 50 characters and contain only letters and spaces",
    errMobileInvalid: "Mobile number must be a valid 10-digit number starting with 6, 7, 8, or 9",
    errPasswordInvalid: "Password must be at least 6 characters long",
    register: "Register",
    alreadyRegistered: "Already registered?",
    loginHere: "Login here",
    sendOtp: "Send OTP",
    sending: "Sending...",
    resendOtp: "Resend OTP",
    enterOtp: "Enter OTP",
    verifyOtp: "Verify OTP",
    verified: "Verified",
    otpSentMsg: "OTP has been sent to your mobile number via SMS. Valid for 10 minutes.",
    otpVerifySuccess: "Mobile number verified successfully!",
    otpVerifyError: "Invalid OTP. Please try again.",
    otpExpiredError: "OTP has expired. Please request a new one.",
    otpSendError: "Failed to send OTP. Please check your number and try again.",
    changeNumber: "Change Number",
    welcomeUser: "Welcome, {name}",
    classBadge: "Class",
    schoolBadge: "School",
    pushedExams: "Pushed Examinations",
    noExams: "No exams currently pushed for your school or classroom group.",
    duration: "Duration",
    mins: "Mins",
    maxMarks: "Max Marks",
    completed: "Completed",
    notStarted: "Take Exam",
    inProgress: "Resume Exam",
    questionOf: "Question {current} of {total}",
    timer: "Timer",
    questionNavigator: "Question Navigator",
    previous: "Previous",
    next: "Next",
    submitExam: "Submit Examination",
    submitting: "Submitting...",
    confirmSubmit: "Are you sure you want to submit the exam?",
    confirmUnanswered: " You have left {count} questions unanswered.",
    congratulations: "Congratulations!",
    successSubmitDesc: "You have successfully completed and submitted the examination. Your participation has been recorded in the database system.",
    downloadCertificate: "Download Participation Certificate",
    backToDashboard: "Back to Dashboard",
    loading: "Loading system...",
    
    // Admin translations
    adminPanelTitle: "ONLINE EXAM MANAGEMENT SYSTEM: ADMIN PANEL",
    studentPortalTitle: "ONLINE EXAM PORTAL",
    superAdminPortalTitle: "SUPER ADMIN DASHBOARD",
    logout: "Logout",
    signedInAs: "Signed in as",
    
    // Admin Tabs
    tabAnalytics: "Analytics Dashboard",
    tabSchools: "Seeding Schools",
    tabClassrooms: "Classrooms & Groups",
    tabCategories: "Categories & Questions",
    tabExams: "Exams Pushing",
    
    // Admin Analytics Tab
    analyticsOverview: "Overview Statistics",
    analyticsTotalSchools: "Total Schools",
    analyticsTotalClassrooms: "Total Classrooms",
    analyticsTotalExams: "Total Exams",
    analyticsTotalStudents: "Total Registered Students",
    analyticsTotalAttempts: "Total Exam Attempts",
    analyticsAverageScore: "Average Score Percentage",
    analyticsRecentAttempts: "Recent Exam Attempts",
    analyticsTopLeaderboard: "Top 3 Leaderboard",
    analyticsExport: "Classroom Group Results Export",
    analyticsSelectGroup: "Select Classroom Group",
    analyticsSelectSchool: "Select School",
    analyticsExportCsv: "Export Results to CSV",
    analyticsLoading: "Loading analytics dashboard...",
    analyticsClearFilters: "Clear Filters",
    analyticsRegTrends: "Student Registration Trends (Last 7 Days)",
    analyticsScoreBreakdown: "Exam Average Score Breakdown",
    analyticsGradeDistribution: "Performance Grade Distribution",
    analyticsClassroomPerformance: "Classroom Performance Analytics",
    analyticsLeaderboardTitle: "Top-3 Participation Leaderboard",
    analyticsExamNameRequired: "Exam Name (Required)",
    analyticsSelectExamPlaceholder: "-- Select Exam --",
    analyticsGroupOptional: "Group (Optional)",
    analyticsAllGroupsPlaceholder: "-- All Groups --",
    analyticsFromDateTime: "From Date & Time",
    analyticsToDateTime: "To Date & Time",
    analyticsClearLeaderboardFilters: "Clear Leaderboard Filters",
    analyticsDownloadCsvReport: "Download CSV Report",
    analyticsFetchingLeaderboard: "Fetching leaderboard...",
    analyticsSelectExamToLoad: "Please select an exam to load rankings.",
    analyticsNoStudentCompleted: "No student completed this exam yet under the selected filters.",
    analyticsLeaderboardRank: "Rank",
    analyticsLeaderboardStudentName: "Student Name",
    analyticsLeaderboardClass: "Class",
    analyticsLeaderboardSchoolName: "School Name",
    analyticsLeaderboardScore: "Score",
    analyticsLeaderboardCertificate: "Certificate",
    analyticsLeaderboardTotal: "Total",
    analyticsLeaderboardMarks: "marks",
    analyticsNoRegData: "No registration data.",
    analyticsNoPerfData: "No exam performance data.",
    analyticsNoScoreRecords: "No attempt score records.",
    analyticsNoClassroomData: "No classroom performance data yet.",
    analyticsClassroomColName: "Classroom Name",
    analyticsClassroomColStudents: "Students",
    analyticsClassroomColAttempts: "Completed Attempts",
    analyticsClassroomColAvgScore: "Average Score",
    
    // Admin Schools Tab
    schoolsSeedDatabase: "Seed Schools Database",
    schoolsCsvUploadDesc: "Upload a CSV list of schools. Format: School Name, UDISE Number, Tehsil, District (Tehsil and District columns are optional).",
    schoolsCsvData: "CSV / Excel Data",
    schoolsLang: "School Data Language",
    schoolsSeedBtn: "Seed Schools",
    schoolsSeedingInProgress: "Seeding Schools...",
    schoolsManagedSchools: "Managed Schools",
    schoolsSearchPlaceholder: "Search school name or UDISE...",
    schoolsShowLabel: "Show",
    schoolsColName: "School Name",
    schoolsColUdise: "UDISE No.",
    schoolsColTehsil: "Tehsil",
    schoolsColDistrict: "District",
    schoolsColClassrooms: "Linked Classrooms",
    schoolsColActions: "Actions",
    schoolsNoSchools: "No schools published yet.",
    schoolsEditBtn: "Edit",
    schoolsDeleteBtn: "Delete",
    schoolsDeleteSelected: "Delete Selected",
    schoolsEditSchoolTitle: "Edit School Details",
    schoolsSaveBtn: "Save Changes",
    schoolsCancelBtn: "Cancel",
    
    // Admin Classrooms Tab
    classroomsCreateClass: "Create Classroom",
    classroomsClassName: "Classroom Name",
    classroomsPlaceholderClass: "e.g. Class 10th A",
    classroomsCreateClassBtn: "Create Classroom",
    classroomsCreating: "Creating...",
    classroomsDatabase: "Classrooms Database",
    classroomsNoClassrooms: "No classrooms added yet.",
    classroomsCreateGroup: "Create Classroom Group",
    classroomsGroupName: "Group Name",
    classroomsPlaceholderGroup: "e.g. Grade 10-12 Group",
    classroomsLinkLabel: "Link to Classrooms",
    classroomsCreateGroupBtn: "Create Group",
    classroomsManagedGroups: "Managed Groups",
    classroomsNoGroups: "No classroom groups created yet.",
    
    // Admin Categories Tab
    categoriesCreateCat: "Create Category",
    categoriesCatName: "Category Name",
    categoriesPlaceholderCat: "e.g. Science, Mathematics",
    categoriesSubcats: "Subcategories (Comma separated)",
    categoriesPlaceholderSubcats: "e.g. Biology, Chemistry, Physics",
    categoriesCreateCatBtn: "Create Category",
    categoriesUpdatingCat: "Updating...",
    categoriesEditCatTitle: "Edit Category Settings",
    categoriesUpdateCatBtn: "Update Category",
    categoriesDatabase: "Categories & Subcategories",
    categoriesNoCategories: "No categories added yet.",
    categoriesUploadQuestions: "Upload Questions Pool",
    categoriesCsvDesc: "CSV Columns: Question, Option A, Option B, Option D, Correct Answer (A/B/C/D).",
    categoriesCsvLabel: "CSV / Excel Questions Content",
    categoriesSetName: "Question Set Name (Optional)",
    categoriesPlaceholderSet: "e.g. Set A, Test Pool 1 (leave blank for timestamp default)",
    categoriesUploadBtn: "Upload Questions",
    categoriesUploading: "Uploading Pool...",
    categoriesSelectCatPlaceholder: "-- Select Category --",
    categoriesSubcatOptional: "Subcategory (Optional)",
    categoriesNone: "-- None --",
    categoriesUploadFileLabel: "Upload .csv/.xlsx:",
    categoriesImageSupportTip: "Image Support: You can input image URLs or base64 data URIs inside any Option (A-D) to make them image-based choices. To add a reference image for the question, supply it in the optional 7th column.",
    categoriesCsvPlaceholder: "Question text,Option A,Option B,Option C,Option D,Correct Option,Reference Image (Optional)\nWhat is 2+2?,3,4,5,6,B",
    
    // Admin Exams Tab
    examsCreateExam: "Create & Pushed Exam",
    examsExamName: "Exam Name",
    examsExamNameHindi: "Exam Hindi Name",
    examsPlaceholderName: "e.g. Mid-Term Science Test",
    examsPlaceholderNameHindi: "e.g. मध्यावधि विज्ञान परीक्षा",
    examsQuestionSet: "Question Set",
    examsChooseSet: "-- Choose Question Set --",
    examsDurationLabel: "Duration (Mins)",
    examsQuestionCount: "Question Count",
    examsMarkPerQ: "Mark Per Q",
    examsTargetLang: "Exam Target Language",
    examsPushSchools: "Push to Schools",
    examsTargetGroups: "Target Classroom Groups",
    examsCreateBtn: "Create & Push Exam",
    examsPushedDatabase: "Pushed Exams Database",
    examsEditTitle: "Edit Exam Settings",
    examsUpdateBtn: "Update Exam Settings",
    examsNoExams: "No exams published yet.",
    adminSelectAll: "Select All",
    adminClearSelection: "Clear Selection",
    adminPushSelected: "Push selected",
    adminDeleteSelected: "Delete selected",
    adminEditBtn: "Edit",
    adminDeleteBtn: "Delete",
    adminPushBtn: "Push",
    adminCancelBtn: "Cancel",
    adminSaveChangesBtn: "Save Changes",
    adminNoSchools: "No schools",
    adminNoClassesLinked: "No classes linked",
    adminSrNo: "Sr. No.",
    adminPrevious: "Previous",
    adminNext: "Next",
    adminShowingText: "Showing",
    adminEntriesText: "entries",
    adminOfText: "of",
    adminSchoolsText: "schools",
    adminFilteredFromText: "filtered from",
    adminTotalText: "total",
    adminNoMatchingSchools: "No matching schools found.",
    adminAllDistricts: "-- All Districts --",
    adminAllTehsils: "-- All Tehsils --",
    adminSchoolsList: "Schools List",
    adminTehsilPlaceholder: "e.g. Tehsil Name",
    adminDistrictPlaceholder: "e.g. District Name",
    adminNoClassroomsYet: "No classrooms created yet. Create classrooms in the \"Classrooms & Groups\" tab.",
    adminContains: "Contains",
    adminSetupGroups: "Setup Groups",
    adminGroupPlaceholder: "e.g. 5th to 8th Group A",
    adminSelectClassroomsInGroup: "Select Classrooms in Group",
    adminCreateGroup: "Create Group",
    adminCurrentGroups: "Current Groups",
    adminPushClassroomToSchools: "Push Classroom to Schools",
    adminSelectSchoolsToPushDesc: "Select the schools to link/push classroom",
    adminEditClassroomName: "Edit Classroom Name",
    adminEditGroupDetails: "Edit Group Details",
    adminUpdateGroup: "Update Group",
    adminQuestionSet: "Question Set",
    adminNoQuestionSetsUploaded: "No question sets uploaded yet for this category. Please seed questions first.",
    adminSelectedAutomatically: "(Selected automatically)",
    adminCreatingExam: "Creating Exam...",
    adminActiveExamsList: "Active Exams List",
    adminExamName: "Exam Name",
    adminTargetScope: "Target Scope",
    adminStats: "Stats",
    adminActions: "Actions",
    adminPool: "Pool",
    adminAttempts: "Attempts",
    adminTargetSchoolsLabel: "Schools",
    adminTargetGroupsLabel: "Groups",
    adminDefaultSet: "Default Set",
    adminMins: "Mins",
    adminPlaceholderQCount: "e.g. 50",
    adminPlaceholderMarks: "e.g. 2",
    adminPushToSchools: "Push to Schools",
    pendingApprovalMsg: "A student with this name is already registered in this classroom. Your registration is pending admin approval.",
    approvals: "Approvals",
    pendingApprovals: "Pending Approvals",
    studentApprovals: "Student Registration Approvals",
    approve: "Approve",
    reject: "Reject",
    noPendingApprovals: "No pending registration approvals.",
    successApprove: "Student registration approved successfully.",
    successReject: "Student registration rejected.",
    checkStatusBtn: "Check Status",
    checkingStatusBtn: "Checking status...",
  },
  hi: {
    languageLabel: "भाषा / Language",
    studentLogin: "छात्र लॉगिन",
    welcome: "स्वागत है",
    subWelcome: "ऑनलाइन स्कूल परीक्षा प्रबंधन प्रणाली",
    emailOrMobile: "ईमेल या मोबाइल नंबर",
    placeholderEmailMobile: "अपना ईमेल या मोबाइल नंबर दर्ज करें",
    password: "पासवर्ड",
    placeholderPassword: "पासवर्ड दर्ज करें",
    showPassword: "पासवर्ड दिखाएं",
    signIn: "लॉगिन करें",
    authenticating: "सत्यापित किया जा रहा है...",
    areYouStudent: "क्या आप छात्र हैं?",
    registerHere: "यहाँ पंजीकरण करें",
    studentRegistration: "छात्र पंजीकरण",
    subRegister: "परीक्षा में शामिल होने के लिए पंजीकरण करें",
    fullName: "पूरा नाम",
    placeholderName: "अपना नाम दर्ज करें",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    placeholderFirstName: "पहला नाम दर्ज करें",
    placeholderLastName: "अंतिम नाम दर्ज करें",
    errFirstNameInvalid: "पहला नाम 1 से 25 वर्णों के बीच होना चाहिए और इसमें केवल अक्षर और स्थान होने चाहिए",
    errLastNameInvalid: "अंतिम नाम 1 से 25 वर्णों के बीच होना चाहिए और इसमें केवल अक्षर और स्थान होने चाहिए",
    schoolUdise: "स्कूल का नाम / यूडीआईएसई संख्या",
    placeholderSearchSchool: "खोजने के लिए स्कूल का नाम या यूडीआईएसई टाइप करें...",
    classClassroom: "कक्षा / क्लासरूम",
    selectClass: "-- कक्षा चुनें --",
    selectSchoolFirst: "कृपया पहले स्कूल का चयन करें।",
    district: "जिला",
    tehsil: "तहसील",
    mobileUnique: "मोबाइल नंबर (अद्वितीय लॉगिन आईडी)",
    placeholderMobile: "10-अंकों का मोबाइल नंबर",
    choosePassword: "पासवर्ड चुनें",
    registering: "पंजीकरण हो रहा है...",
    errNameInvalid: "नाम 2 से 50 वर्णों के बीच होना चाहिए और इसमें केवल अक्षर और स्थान होने चाहिए",
    errMobileInvalid: "मोबाइल नंबर 6, 7, 8 या 9 से शुरू होने वाला 10-अंकीय मान्य नंबर होना चाहिए",
    errPasswordInvalid: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
    register: "पंजीकरण करें",
    alreadyRegistered: "पहले से पंजीकृत हैं?",
    loginHere: "यहाँ लॉगिन करें",
    sendOtp: "OTP भेजें",
    sending: "भेज रहा है...",
    resendOtp: "OTP पुनः भेजें",
    enterOtp: "OTP दर्ज करें",
    verifyOtp: "OTP सत्यापित करें",
    verified: "सत्यापित",
    otpSentMsg: "आपके मोबाइल नंबर पर SMS द्वारा OTP भेजा गया है। यह 10 मिनट के लिए मान्य है।",
    otpVerifySuccess: "मोबाइल नंबर सफलतापूर्वक सत्यापित किया गया!",
    otpVerifyError: "अमान्य OTP। कृपया पुनः प्रयास करें।",
    otpExpiredError: "OTP समाप्त हो गया है। कृपया नया अनुरोध करें।",
    otpSendError: "OTP भेजने में विफल। कृपया अपना नंबर जांचें और पुनः प्रयास करें।",
    changeNumber: "नंबर बदलें",
    welcomeUser: "स्वागत है, {name}",
    classBadge: "कक्षा",
    schoolBadge: "स्कूल",
    pushedExams: "जारी की गई परीक्षाएं",
    noExams: "आपके स्कूल या क्लासरूम ग्रुप के लिए वर्तमान में कोई परीक्षा जारी नहीं की गई है।",
    duration: "अवधि",
    mins: "मिनट",
    maxMarks: "अधिकतम अंक",
    completed: "पूर्ण",
    notStarted: "परीक्षा दें",
    inProgress: "परीक्षा जारी रखें",
    questionOf: "प्रश्न {current} का {total}",
    timer: "समय",
    questionNavigator: "प्रश्न नेविगेटर",
    previous: "पिछला",
    next: "अगला",
    submitExam: "परीक्षा जमा करें",
    submitting: "जमा किया जा रहा है...",
    confirmSubmit: "क्या आप वाकई परीक्षा जमा करना चाहते हैं?",
    confirmUnanswered: " आपने {count} प्रश्नों के उत्तर नहीं दिए हैं।",
    congratulations: "बधाई हो!",
    successSubmitDesc: "आपने सफलतापूर्वक परीक्षा पूरी कर ली है और जमा कर दी है। आपकी भागीदारी डेटाबेस सिस्टम में दर्ज कर ली गई है।",
    downloadCertificate: "प्रमाण पत्र डाउनलोड करें",
    backToDashboard: "डैशबोर्ड पर वापस जाएं",
    loading: "सिस्टम लोड हो रहा है...",
    
    // Admin translations
    adminPanelTitle: "ऑनलाइन परीक्षा प्रबंधन प्रणाली: एडमिन पैनल",
    studentPortalTitle: "ऑनलाइन परीक्षा पोर्टल",
    superAdminPortalTitle: "सुपर एडमिन डैशबोर्ड",
    logout: "लॉगआउट",
    signedInAs: "लॉगिन उपयोगकर्ता",
    
    // Admin Tabs
    tabAnalytics: "विश्लेषणात्मक डैशबोर्ड",
    tabSchools: "स्कूलों की फीडिंग/सीडिंग",
    tabClassrooms: "कक्षाएं और समूह",
    tabCategories: "श्रेणियां और प्रश्न",
    tabExams: "परीक्षा वितरण",
    
    // Admin Analytics Tab
    analyticsOverview: "सांख्यिकी विवरण",
    analyticsTotalSchools: "कुल स्कूल",
    analyticsTotalClassrooms: "कुल कक्षाएं",
    analyticsTotalExams: "कुल परीक्षाएं",
    analyticsTotalStudents: "कुल पंजीकृत छात्र",
    analyticsTotalAttempts: "कुल प्रयास",
    analyticsAverageScore: "औसत प्रतिशत अंक",
    analyticsRecentAttempts: "हाल के परीक्षा प्रयास",
    analyticsTopLeaderboard: "शीर्ष 3 लीडरबोर्ड",
    analyticsExport: "कक्षा समूह परिणाम निर्यात",
    analyticsSelectGroup: "कक्षा समूह का चयन करें",
    analyticsSelectSchool: "स्कूल का चयन करें",
    analyticsExportCsv: "परिणाम CSV में निर्यात करें",
    analyticsLoading: "एनालिटिक्स डैशबोर्ड लोड हो रहा है...",
    analyticsClearFilters: "फ़िल्टर हटाएं",
    analyticsRegTrends: "छात्र पंजीकरण रुझान (अंतिम 7 दिन)",
    analyticsScoreBreakdown: "परीक्षा औसत अंक विवरण",
    analyticsGradeDistribution: "प्रदर्शन ग्रेड वितरण",
    analyticsClassroomPerformance: "कक्षा प्रदर्शन विश्लेषण",
    analyticsLeaderboardTitle: "शीर्ष-3 सहभागिता लीडरबोर्ड",
    analyticsExamNameRequired: "परीक्षा का नाम (आवश्यक)",
    analyticsSelectExamPlaceholder: "-- परीक्षा चुनें --",
    analyticsGroupOptional: "समूह (वैकल्पिक)",
    analyticsAllGroupsPlaceholder: "-- सभी समूह --",
    analyticsFromDateTime: "प्रारंभिक तिथि और समय",
    analyticsToDateTime: "अंतिम तिथि और समय",
    analyticsClearLeaderboardFilters: "लीडरबोर्ड फ़िल्टर हटाएं",
    analyticsDownloadCsvReport: "CSV रिपोर्ट डाउनलोड करें",
    analyticsFetchingLeaderboard: "लीडरबोर्ड लाया जा रहा है...",
    analyticsSelectExamToLoad: "रैंकिंग लोड करने के लिए कृपया एक परीक्षा चुनें।",
    analyticsNoStudentCompleted: "चयनित फ़िल्टर के तहत अभी तक किसी भी छात्र ने यह परीक्षा पूरी नहीं की है।",
    analyticsLeaderboardRank: "रैंक",
    analyticsLeaderboardStudentName: "छात्र का नाम",
    analyticsLeaderboardClass: "कक्षा",
    analyticsLeaderboardSchoolName: "स्कूल का नाम",
    analyticsLeaderboardScore: "प्राप्तांक",
    analyticsLeaderboardCertificate: "प्रमाण पत्र",
    analyticsLeaderboardTotal: "कुल",
    analyticsLeaderboardMarks: "अंक",
    analyticsNoRegData: "कोई पंजीकरण डेटा नहीं है।",
    analyticsNoPerfData: "कोई परीक्षा प्रदर्शन डेटा नहीं है।",
    analyticsNoScoreRecords: "कोई परीक्षा परिणाम रिकॉर्ड नहीं है।",
    analyticsNoClassroomData: "अभी तक कोई कक्षा प्रदर्शन डेटा उपलब्ध नहीं है।",
    analyticsClassroomColName: "कक्षा का नाम",
    analyticsClassroomColStudents: "छात्रों की संख्या",
    analyticsClassroomColAttempts: "पूर्ण परीक्षा प्रयास",
    analyticsClassroomColAvgScore: "औसत प्राप्तांक",
    
    // Admin Schools Tab
    schoolsSeedDatabase: "स्कूल डेटाबेस फीड करें",
    schoolsCsvUploadDesc: "स्कूलों की CSV सूची अपलोड करें। प्रारूप: स्कूल का नाम, यूडीआईएसई संख्या, तहसील, जिला (तहसील और जिला वैकल्पिक हैं)।",
    schoolsCsvData: "CSV / Excel डेटा",
    schoolsLang: "स्कूल डेटा भाषा",
    schoolsSeedBtn: "स्कूलों को सीड/फीड करें",
    schoolsSeedingInProgress: "स्कूलों को सीड किया जा रहा है...",
    schoolsManagedSchools: "प्रबंधित स्कूल",
    schoolsSearchPlaceholder: "स्कूल का नाम या यूडीआईएसई खोजें...",
    schoolsShowLabel: "दिखाएं",
    schoolsColName: "स्कूल का नाम",
    schoolsColUdise: "यूडीआईएसई संख्या",
    schoolsColTehsil: "तहसील",
    schoolsColDistrict: "जिला",
    schoolsColClassrooms: "लिंक्ड कक्षाएं",
    schoolsColActions: "कार्रवाई",
    schoolsNoSchools: "अभी तक कोई स्कूल नहीं डाला गया है।",
    schoolsEditBtn: "संपादित करें",
    schoolsDeleteBtn: "हटाएं",
    schoolsDeleteSelected: "चयनित हटाएं",
    schoolsEditSchoolTitle: "स्कूल विवरण संपादित करें",
    schoolsSaveBtn: "परिवर्तन सहेजें",
    schoolsCancelBtn: "रद्द करें",
    
    // Admin Classrooms Tab
    classroomsCreateClass: "कक्षा बनाएं",
    classroomsClassName: "कक्षा का नाम",
    classroomsPlaceholderClass: "जैसे. कक्षा 10वीं अ",
    classroomsCreateClassBtn: "कक्षा बनाएं",
    classroomsCreating: "बनाया जा रहा है...",
    classroomsDatabase: "कक्षाएं डेटाबेस",
    classroomsNoClassrooms: "अभी तक कोई कक्षा नहीं जोड़ी गई है।",
    classroomsCreateGroup: "कक्षा समूह बनाएं",
    classroomsGroupName: "समूह का नाम",
    classroomsPlaceholderGroup: "जैसे. कक्षा 10-12 समूह",
    classroomsLinkLabel: "कक्षाओं को लिंक करें",
    classroomsCreateGroupBtn: "समूह बनाएं",
    classroomsManagedGroups: "प्रबंधित समूह",
    classroomsNoGroups: "अभी तक कोई कक्षा समूह नहीं बनाया गया है।",
    
    // Admin Categories Tab
    categoriesCreateCat: "श्रेणी बनाएं",
    categoriesCatName: "श्रेणी का नाम",
    categoriesPlaceholderCat: "जैसे. विज्ञान, गणित",
    categoriesSubcats: "उपश्रेणियाँ (अल्पविराम से अलग)",
    categoriesPlaceholderSubcats: "जैसे. जीव विज्ञान, रसायन विज्ञान, भौतिकी",
    categoriesCreateCatBtn: "श्रेणी बनाएं",
    categoriesUpdatingCat: "अद्यतन किया जा रहा है...",
    categoriesEditCatTitle: "श्रेणी सेटिंग्स संपादित करें",
    categoriesUpdateCatBtn: "श्रेणी अद्यतन करें",
    categoriesDatabase: "श्रेणियाँ और उपश्रेणियाँ",
    categoriesNoCategories: "अभी तक कोई श्रेणी नहीं जोड़ी गई है।",
    categoriesUploadQuestions: "प्रश्न पूल अपलोड करें",
    categoriesCsvDesc: "CSV कॉलम: प्रश्न, विकल्प A, विकल्प B, विकल्प C, विकल्प D, सही विकल्प (A/B/C/D)।",
    categoriesCsvLabel: "CSV / Excel प्रश्न सामग्री",
    categoriesSetName: "प्रश्न सेट का नाम (वैकल्पिक)",
    categoriesPlaceholderSet: "जैसे. सेट अ, टेस्ट पूल 1 (खाली छोड़ें तो समय आटोमेटिक ले लेगा)",
    categoriesUploadBtn: "प्रश्न अपलोड करें",
    categoriesUploading: "पूल अपलोड हो रहा है...",
    categoriesSelectCatPlaceholder: "-- श्रेणी चुनें --",
    categoriesSubcatOptional: "उपश्रेणी (वैकल्पिक)",
    categoriesNone: "-- कोई नहीं --",
    categoriesUploadFileLabel: "अपलोड .csv/.xlsx:",
    categoriesImageSupportTip: "इमेज सपोर्ट: आप किसी भी विकल्प (A-D) के अंदर इमेज यूआरएल या बेस64 डेटा यूआरआई डाल सकते हैं ताकि वे इमेज-आधारित विकल्प बन सकें। प्रश्न के लिए संदर्भ इमेज जोड़ने के लिए, इसे वैकल्पिक 7वें कॉलम में प्रदान करें।",
    categoriesCsvPlaceholder: "प्रश्न पाठ,विकल्प A,विकल्प B,विकल्प C,विकल्प D,सही विकल्प,संदर्भ इमेज (वैकल्पिक)\nभारत की राजधानी क्या है?,मुंबई,नई दिल्ली,कोलकाता,चेन्नई,B",
    
    // Admin Exams Tab
    examsCreateExam: "परीक्षा बनाएं और जारी करें",
    examsExamName: "परीक्षा का नाम",
    examsExamNameHindi: "परीक्षा का हिंदी नाम",
    examsPlaceholderName: "जैसे: मध्यावधि विज्ञान परीक्षा",
    examsPlaceholderNameHindi: "जैसे: मध्यावधि विज्ञान परीक्षा (हिंदी में)",
    examsQuestionSet: "प्रश्न सेट",
    examsChooseSet: "-- प्रश्न सेट चुनें --",
    examsDurationLabel: "अवधि (मिनट)",
    examsQuestionCount: "प्रश्नों की संख्या",
    examsMarkPerQ: "प्रति प्रश्न अंक",
    examsTargetLang: "परीक्षा लक्षित भाषा",
    examsPushSchools: "स्कूलों में भेजें",
    examsTargetGroups: "लक्षित कक्षा समूह",
    examsCreateBtn: "परीक्षा बनाएं और जारी करें",
    examsPushedDatabase: "जारी की गई परीक्षा डेटाबेस",
    examsEditTitle: "परीक्षा सेटिंग्स संपादित करें",
    examsUpdateBtn: "परीक्षा सेटिंग्स सहेजें",
    examsNoExams: "अभी तक कोई परीक्षा जारी नहीं की गई है।",
    adminSelectAll: "सभी चुनें",
    adminClearSelection: "चयन साफ करें",
    adminPushSelected: "चयनित पुश करें",
    adminDeleteSelected: "चयनित हटाएं",
    adminEditBtn: "संपादित करें",
    adminDeleteBtn: "हटाएं",
    adminPushBtn: "पुश करें",
    adminCancelBtn: "रद्द करें",
    adminSaveChangesBtn: "परिवर्तन सहेजें",
    adminNoSchools: "कोई स्कूल नहीं",
    adminNoClassesLinked: "कोई कक्षा लिंक नहीं",
    adminSrNo: "क्र. सं.",
    adminPrevious: "पिछला",
    adminNext: "अगला",
    adminShowingText: "दिखाया जा रहा है",
    adminEntriesText: "प्रविष्टियाँ",
    adminOfText: "में से",
    adminSchoolsText: "स्कूल",
    adminFilteredFromText: "फ़िल्टर किया गया",
    adminTotalText: "कुल",
    adminNoMatchingSchools: "कोई मिलान वाले स्कूल नहीं मिले।",
    adminAllDistricts: "-- सभी जिले --",
    adminAllTehsils: "-- सभी तहसील --",
    adminSchoolsList: "स्कूलों की सूची",
    adminTehsilPlaceholder: "जैसे. तहसील का नाम",
    adminDistrictPlaceholder: "जैसे. जिले का नाम",
    adminNoClassroomsYet: "अभी तक कोई कक्षा नहीं बनाई गई है। कक्षाएं और समूह टैब में कक्षाएं बनाएं।",
    adminContains: "शामिल हैं",
    adminSetupGroups: "समूह बनाएं",
    adminGroupPlaceholder: "जैसे. 5वीं से 8वीं समूह अ",
    adminSelectClassroomsInGroup: "समूह में कक्षाएं चुनें",
    adminCreateGroup: "समूह बनाएं",
    adminCurrentGroups: "वर्तमान समूह",
    adminPushClassroomToSchools: "कक्षा को स्कूलों में पुश करें",
    adminSelectSchoolsToPushDesc: "कक्षा को लिंक/पुश करने के लिए स्कूल चुनें",
    adminEditClassroomName: "कक्षा का नाम संपादित करें",
    adminEditGroupDetails: "समूह विवरण संपादित करें",
    adminUpdateGroup: "समूह अपडेट करें",
    adminQuestionSet: "प्रश्न सेट",
    adminNoQuestionSetsUploaded: "इस श्रेणी के लिए अभी तक कोई प्रश्न सेट अपलोड नहीं किया गया है। कृपया पहले प्रश्न अपलोड करें।",
    adminSelectedAutomatically: "(स्वचालित रूप से चयनित)",
    adminCreatingExam: "परीक्षा बनाई जा रही है...",
    adminActiveExamsList: "सक्रिय परीक्षा सूची",
    adminExamName: "परीक्षा का नाम",
    adminTargetScope: "लक्षित दायरा",
    adminStats: "आंकड़े",
    adminActions: "कार्रवाई",
    adminPool: "पूल",
    adminAttempts: "प्रयास",
    adminTargetSchoolsLabel: "स्कूल",
    adminTargetGroupsLabel: "समूह",
    adminDefaultSet: "डिफ़ॉल्ट सेट",
    adminMins: "मिनट",
    adminPlaceholderQCount: "जैसे. 50",
    adminPlaceholderMarks: "जैसे. 2",
    adminPushToSchools: "स्कूलों में भेजें",
    pendingApprovalMsg: "इस कक्षा में इस नाम का एक छात्र पहले से ही पंजीकृत है। आपका पंजीकरण व्यवस्थापक (Admin) की मंजूरी के लिए लंबित है।",
    approvals: "मंजूरी",
    pendingApprovals: "लंबित मंजूरियां",
    studentApprovals: "छात्र पंजीयन मंजूरियां",
    approve: "मंजूर करें",
    reject: "अस्वीकार करें",
    noPendingApprovals: "कोई लंबित पंजीयन मंजूरी नहीं है।",
    successApprove: "छात्र पंजीयन सफलतापूर्वक मंजूर किया गया।",
    successReject: "छात्र पंजीयन अस्वीकार कर दिया गया।",
    checkStatusBtn: "स्थिति जांचें",
    checkingStatusBtn: "स्थिति जांची जा रही है...",
  }
} as const;

export type Language = keyof typeof translations;
